local path = minetest.get_modpath("music_default")
dofile(path .. "/surface_day.lua")
dofile(path .. "/surface_night.lua")
dofile(path .. "/underground_1.lua")
dofile(path .. "/underground_2.lua")
dofile(path .. "/underground_3.lua")
